version: "3.11"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: doc_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: documents_db
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://doc_user:123456@db/documents_db

