"""Remove title and content fields

Revision ID: ba7dfbcd6c6d
Revises: 6fadc438feb2
Create Date: 2024-09-06 20:04:09.921123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7dfbcd6c6d'
down_revision: Union[str, None] = '6fadc438feb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_content', table_name='documents')
    op.drop_index('ix_documents_title', table_name='documents')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_documents_title', 'documents', ['title'], unique=False)
    op.create_index('ix_documents_content', 'documents', ['content'], unique=False)
    # ### end Alembic commands ###
